#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           /bin/ksh Gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», ««var»», «${var}», «${var:-default}», «${var:+alt}»,
#           «${var:?error}», «$( command )», «$( ( expr ) )», «`command`», «`expr`»,
#           «${#var}», «${var%pattern}», «${var##pattern}», «${var%%pattern}»,
#           «${var#pattern}», «$( command )»», ««( expr )»»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including: «command», «set», «ulimit».
#
#   Important for editing:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc. In particular, it does NOT use «local» because
#       that is not implemented by dash(1). See:
#         https://pubs.opengroup.org/onlinepubs/007904975/utilities/xcu_chap02.html#tag_02_09_01
#
#       It does NOT use «typeset» because that is often implemented as an alias
#       for «local». It does NOT use «export VAR=val» because that is often
#       implemented as an alias for «VAR=val; export VAR».
#
#   (3) This script was generated by Gradle.
#
#       Any attempt to edit it manually must be followed by testing to ensure
#       that it works with all POSIX shells.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link:             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC2039,SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --unix "$JAVACMD" )
    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in #(
              -*)   false ;; # don't mess with options #(
              /?*)  t=${arg#)}; t=/${t%%/*} #(
                    [ -e "$t" ] ) ;; #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # temporary variables assigned, so each argument winds up back in the
        # temporary variable previously (and cycle) assigned to it.
        shift                   # remove $arg
        set -- "$@" "$arg"      # push $arg onto the end
    done
fi


# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command:
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, GRADLE_OPTS, and optsEnvironmentVar are not
#     temporary variable names; see the corresponding environment variable definitions.
#   * The complexity here is that options containing spaces must be properly quoted.
#   * The "stacking" of options is done to simplify the processing of quotes.
#   * A special case is when optsEnvironmentVar contains shell operators like '>&2'
#     that must be passed through to Java but cannot be put inside a Java option.
#     The solution is to have a separate 'optsOperators' variable that is appended
#     to JAVA_OPTS (after GRADLE_OPTS).

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xeli" or "da" options are used when Gradle has not been started yet.
# These options are used by Gradle's daemon to communicate with the running Gradle process.
# The 'xeli' option is used to request that the existing process exits.
# The 'da' option is used to request information about the existing process.
case "$*" in #(
  *--xeli | *--xeli\ | *--xeli=*)  exit 0 ;; #(
  *--da   | *--da\   | *--da=*)    exit 0 ;;
esac

# Use "xargs" to parse quoted args.
#
# With -n://1//, we process at most one arg per execution.
# With default POSIX xargs, we need to use 'sh -c' to handle args containing spaces.
#
# shellcheck disable=SC2015
exec \
    xargs -n://1// sh -c 'shift; "$@"' -- "$JAVACMD" \
        "$@"